apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Values.metadata.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort:  {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "{{ .Values.service.port }}"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"


    
