image:
  repository: confluentinc/cp-zookeeper
  tag: 7.0.1
  imagePullPolicy: IfNotPresent

replicas: 1

metadata:
  name: zookeeper
  namespace: zookeeper
  labels:
    app: zookeeper

service:
  name: zookeeper
  type: ClusterIP
  port: 2181
  targetPort: 2181
  protocol: TCP
  selector:
    app: zookeeper

